### ISSUE TITLE
「ハンズオン事前準備」へのリンクがない。

### ISSUE THREAD

**Issue by tsahara** [iij/bootcamp#54]
サイトトップや「IIJ Bootcampとは？」に [「ハンズオン事前準備」](https://iij.github.io/bootcamp/init/hello-bootcamp/) へのリンクがありません。少なくとも「開発環境をdockerで構築」は事前準備が実施されたことを前提としているため、事前準備を実施しないままカリキュラムの学習を始めてしまわないように誘導した方が良いと思います。

**Comment by gitnira** [comment]
#116 で修正PRを投げました

**Comment by gitnira** [comment]
いい感じに出来てそうなのでクローズします
[サイトトップ](https://iij.github.io/bootcamp/#_2022%E5%B9%B4%E5%BA%A6%E3%82%AB%E3%83%AA%E3%82%AD%E3%83%A5%E3%83%A9%E3%83%A0%E4%B8%80%E8%A6%A7)

**Comment by tsahara** [comment]
いい感じですね。修正ありがとうございました。
